name: "Shell"
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'command'
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - run: ${{ github.event.inputs.command }}
    env:
      GIT_COMMITTER_NAME: GitHub Actions
      GIT_AUTHOR_NAME: GitHub Actions
      EMAIL: github-actions[bot]@users.noreply.github.com
